# Предложения
## Получить список предложений
GET http://localhost:5500/offers HTTP/1.1
Content-Type: application/json

###

## Получить список премиальных предложений
GET http://localhost:5500/offers/premium?limit=1 HTTP/1.1
Content-Type: application/json

###

## Получить информацию по предложению
GET http://localhost:5500/offers/6649dee48068962011aea3c0 HTTP/1.1
Content-Type: application/json

###

## Добавить новый оффер
POST http://localhost:5500/offers/create HTTP/1.1
Content-Type: application/json

{
  "title": "11122Новое предложение!!!",
  "description": "Самый новый офеер и тдто",
  "postDate": "2024-05-19T11:13:40.453Z",
  "city": "Paris",
  "previewImage": "AVATAR.jpg",
  "images": ["img.1.png"],
  "isPremius": false,
  "propertyType": "Apartment",
  "rooms": 3,
  "guests": 2,
  "price": 200,
  "supplies": ["Washer", "Towels"],
  "location": { "latitude": 11,  "longitude": 22 },
  "userId": "6649dee48068962011aea3be"
}

###

## Обновить оффер
PATCH http://localhost:5500/offers/6657873c45613839fbd30796 HTTP/1.1
Content-Type: application/json

{
  "title": "Обновили предложение!!!",
  "description": "Обновили старый оффер"
}

###

## Удалить оффер
DELETE http://localhost:5500/offers/6657834b2efff4f283e01c5b HTTP/1.1
Content-Type: application/json

###